version: '3.9'

services:
  db:
    image: postgres:latest
    healthcheck:
      test: [ "CND-SHELL", "pg_isready -U user password -d app" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
    restart: unless-stopped
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5431:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    environment:
      - API_KEY=
    depends_on:
      - db
